### ISSUE TITLE
Doesn't build with gcc4.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#103]
```
Since Archlinux has upgraded to the new gcc4.6 I cannot build this anymore 
(from user repo or from svn sources).

Replacing every "NULL" with "nullptr" and enabling c++0x (in CMakeLists.txt, 
add "-std=c++0x" to "set(CMAKE_???_FLAGS...)") helps for me, but you will 
probably not want to use c++0x now.

What steps will reproduce the problem?
1. Compile it with gcc 4.6, svn head (r481)

What is the expected output? What do you see instead?
Expected: library. Result: error message:
src/ptr_vector.h:31:21: error: ‘NULL’ was not declared in this scope


```

Original issue reported on code.google.com by `opatut...@googlemail.com` on 30 Apr 2011 at 4:12
