### ISSUE TITLE
MSVC DLL build fails with: 'm_amount': redefinition; different storage class

### ISSUE THREAD

**Issue by PhilipDeegan** [jbeder/yaml-cpp#1050]
can be seen at https://github.com/jbeder/yaml-cpp/pull/1049

```
src\\node_data.cpp(16): error C2370: 'm_amount': redefinition; different storage class
include\yaml-cpp/node/detail/node.h(172): note: see declaration of 'm_amount'
```

introduced in #984

**Comment by PhilipDeegan** [comment]
fixed in https://github.com/jbeder/yaml-cpp/pull/1056
