### ISSUE TITLE
Write(_Null) naming conflicts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#171]
```
What is the problem?

Emitter& Write(const _Null& null) - using several libraries that define 'null' 
as a macro, the yaml library will generate compilation errors. Plus, generally 
bad practice to name a variable 'null'.

What version of the product are you using? On what operating system?

Latest master branch (not sure of the version, it's not printed anywhere)
```

Original issue reported on code.google.com by `jballard...@gmail.com` on 19 Sep 2012 at 11:50
