### ISSUE TITLE
yaml-cpp-0.8.0 fails due to missing missing include <cstdint>  with gcc-5.0.0_pre20240804 snapshot

### ISSUE THREAD

**Issue by t-dr** [jbeder/yaml-cpp#1307]
yaml-cpp-0.8.0 fails to compile with most recent gcc-15 snapshot without #include <cstdint>

````
/var/tmp/portage/dev-cpp/yaml-cpp-0.8.0/work/yaml-cpp-0.8.0/src/emitterutils.cpp:221:11: error: ‘uint16_t’ was not declared in this scope
  221 | std::pair<uint16_t, uint16_t> EncodeUTF16SurrogatePair(int codePoint) {
      |           ^~~~~~~~
/var/tmp/portage/dev-cpp/yaml-cpp-0.8.0/work/yaml-cpp-0.8.0/src/emitterutils.cpp:13:1: note: ‘uint16_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   12 | #include "yaml-cpp/null.h"
  +++ |+#include <cstdint>
   13 | #include "yaml-cpp/ostream_wrapper.h"
/var/tmp/portage/dev-cpp/yaml-cpp-0.8.0/work/yaml-cpp-0.8.0/src/emitterutils.cpp:221:21: error: ‘uint16_t’ was not declared in this scope
  221 | std::pair<uint16_t, uint16_t> EncodeUTF16SurrogatePair(int codePoint) {
      |                     ^~~~~~~~
/var/tmp/portage/dev-cpp/yaml-cpp-0.8.0/work/yaml-cpp-0.8.0/src/emitterutils.cpp:221:21: note: ‘uint16_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
/var/tmp/portage/dev-cpp/yaml-cpp-0.8.0/work/yaml-cpp-0.8.0/src/emitterutils.cpp:221:29: error: template argument 1 is invalid
''''

[yaml-cpp-0.8.0-build-failure.log](https://github.com/user-attachments/files/16503819/yaml-cpp-0.8.0-build-failure.log)
[yaml-cpp-0.8.0-build-successful.log](https://github.com/user-attachments/files/16503820/yaml-cpp-0.8.0-build-successful.log)
[yaml-cpp-0.8.0-gcc15-fix.patch](https://github.com/user-attachments/files/16504517/yaml-cpp-0.8.0-gcc15-fix.patch)

**Comment by jbeder** [comment]
Can you submit a PR?

**Comment by Jancs-E** [comment]
I see this labelled as closed, but 0.8.0 still does not compile with GCC 15.2 dying with similar error:

[yaml-cpp-0.8.0-make.log](https://github.com/user-attachments/files/24416723/yaml-cpp-0.8.0-make.log)
