### ISSUE TITLE
regression in 0.5.2

### ISSUE THREAD

**Issue by vks** [jbeder/yaml-cpp#338]
When upgrading from yaml-cpp 0.5.1 to 0.5.2 I get the following compiler error:

```
include/yaml-cpp/node/detail/impl.h: In instantiation of ‘bool YAML::detail::node_data::remove(const Key&, YAML::detail::shared_memory_holder) [with Key = std::basic_string<char>; YAML::detail::shared_memory_holder = boost::shared_ptr<YAML::detail::memory_holder>]’:
include/yaml-cpp/node/detail/node_ref.h:69:40:   required from ‘bool YAML::detail::node_ref::remove(const Key&, YAML::detail::shared_memory_holder) [with Key = std::basic_string<char>; YAML::detail::shared_memory_holder = boost::shared_ptr<YAML::detail::memory_holder>]’
include/yaml-cpp/node/detail/node.h:131:39:   required from ‘bool YAML::detail::node::remove(const Key&, YAML::detail::shared_memory_holder) [with Key = std::basic_string<char>; YAML::detail::shared_memory_holder = boost::shared_ptr<YAML::detail::memory_holder>]’
include/yaml-cpp/node/impl.h:392:58:   required from ‘bool YAML::Node::remove(const Key&) [with Key = std::basic_string<char>]’
include/yaml-cpp/node/detail/impl.h:136:15: error: ‘equals’ was not declared in this scope
     if (equals(*it->first, key, pMemory)) {
               ^
```

This does not happen when using 0.5.1, thus it seems like there is some backwards-incompatible change introduced by 0.5.2.

**Comment by jbeder** [comment]
This is #303, which was fixed; I just haven't created 0.5.3 yet with the patch.
