### ISSUE TITLE
Doesn't compile on OSX 10.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#68]
```
*What steps will reproduce the problem?
1. Including all source into program source tree (instead of using cmake)
2. Compiling

*What is the expected output? What do you see instead?

The failure comes from lines 66:17 in token.h

=========================
        friend std::ostream& operator << (std::ostream& out, const Token& token) {
            out << TokenNames[token.type] << std::string(": ") << token.value;
            for(std::size_t i=0;i<token.params.size();i++)
                out << std::string(" ") << token.params[i];
            return out;
        }

ostream_insert.h:82: error: invalid use of incomplete type 'struct 
std::basic_ostream<char, 
std::char_traits<char> >'
iosfwd:64: error: declaration of 'struct std::basic_ostream<char, 
std::char_traits<char> >'
=========================
These error messages refer to the two `out << ...` lines. If they are commented 
out, the entire 
package compiles and links into the existing source code just fine.

*What version of the product are you using? On what operating system?

yaml-cpp .0.2.5 on OSX 10.6.2.

*Please provide any additional information below.
```

Original issue reported on code.google.com by `sebe...@gmail.com` on 20 Apr 2010 at 10:15
