### ISSUE TITLE
VS2013 (MSVC 18.0.21005.1): error in binary.h (C2610)

### ISSUE THREAD

**Issue by yves84** [jbeder/yaml-cpp#1034]
I get an error when I try to compile yaml-cpp 0.6.3 & 0.7.0.

```
[  1%] Building CXX object CMakeFiles/yaml-cpp.dir/src/binary.cpp.obj
binary.cpp
C:\Users\admin\Desktop\Devel\yaml-cpp-yaml-cpp-0.6.3\include\yaml-cpp/binary.h(26) : error C2610: 'YAML::Binary::Binary(YAML::Binary &&)' : ist keine spezielle Memberfunktion, für die der Standardwert verwendet werden kann
C:\Users\admin\Desktop\Devel\yaml-cpp-yaml-cpp-0.6.3\include\yaml-cpp/binary.h(28) : error C2610: 'YAML::Binary &YAML::Binary::operator =(YAML::Binary &&)' : ist keine spezielle Memberfunktion, für die der Standardwert verwendet werden kann
```

Sry, the error message is in german. Compiling work with Version 0.6.0.

gz

**Comment by TheVice** [comment]
Compiler from VS2013 do not support defaulted move constructor or defaulted move-assignment operator.

See [answer](https://stackoverflow.com/a/24574027) of Roger Rowland for a more details.

**Comment by jbeder** [comment]
I'm closing this because VS2013 is pretty old, and yaml-cpp requires full C++11 support.

**Comment by yves84** [comment]
Update the README

> On Windows, you might use "Visual Studio 12 2013" (VS 2013 32-bits), or "Visual Studio 14 2015 Win64" (VS 2015 64-bits).

Can be a little bit confusing.
