### ISSUE TITLE
Included gtest is too old to compile with MSVC 15.7 / VS 2017.15.7 onwards

### ISSUE THREAD

**Issue by staffantj** [jbeder/yaml-cpp#623]
Attempting to compile the embedded gtest fails under MSVC 15.7 (2017.15.7.x).

```
[CustomBuild] d:\buildagent1\work\dd2dd3ecd59185a2\test\gtest-1.8.0\googletest\include\gtest\internal\gtest-port.h(996, 0): error C2220: warning treated as error - no 'object' file generated [D:\BuildAgent1\work\dd2dd3ecd59185a2\v140\test\googletest_project-prefix\src\googletest_project-build\googlemock\gmock.vcxproj]
[11:20:16][CustomBuild] d:\buildagent1\work\dd2dd3ecd59185a2\test\gtest-1.8.0\googletest\include\gtest\internal\gtest-port.h(996, 0): warning C4996: 'std::tr1': warning STL4002: The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning. [D:\BuildAgent1\work\dd2dd3ecd59185a2\v140\test\googletest_project-prefix\src\googletest_project-build\googlemock\gmock.vcxproj]
[11:20:16][CustomBuild]   c:\vs15\vc\tools\msvc\14.14.26428\include\tuple(1163): note: see declaration of 'std::tr1'
[11:20:16]
```

This was fixed in gtest-1.8.1 over a year ago [](https://github.com/google/googletest/commit/77380cddf77133b98a16b5427ac732648233de29)

**Comment by staffantj** [comment]
[](https://github.com/google/googletest/commit/77380cddf77133b98a16b5427ac732648233de29)

**Comment by staffantj** [comment]
https://github.com/google/googletest/commit/77380cddf77133b98a16b5427ac732648233de29

**Comment by sigmasoldi3r** [comment]
Any directions to fix this?

I'm using also MSVC 17 and I've got 24 errors (C1083) related to googletest.

**Comment by peterchen-cp** [comment]
I got the current head (b87c76a2ef4f974e2739a2d410ee5e36122cfc00) to build with the following changes:

 - for MSVC (15.9.6), install VS2015 toolset (v1400)
 - replace content of test/gtest-1.8.0/  with the content of gtest 1.8.1 (01148677a937eae1c0fd1e488ca81445531ea368)
   I didn't change the name of the folder, of course
 - create an x86 configuration
 - select gmock.sln as target (the second one, which uses the v1400 toolset), 
 - build it
 - in test/CMakeLists.txt, replaced 
    ${PROJECT_BINARY_DIR}/test/prefix/lib/${CMAKE_STATIC_LIBRARY_PREFIX}gmock${CMAKE_STATIC_LIBRARY_SUFFIX}
   by the absolute path of gmock.lib 
 - in /CMakeLists.txt, for
   option(MSVC_SHARED_RT "MSVC: Build with shared runtime libs (/MD)" ON)
   change ON to OFF
 - select run-tests as target, and build it

While figuring out these changes, I had to run "CMake/Cache/Clear Cache Folder" and "CMake/Cache/Generate" from the menu a few times.

This is my first encounter with both CMake and MSVC's CMake "support", so I'm just fiddling around. Good luck.

**Comment by julianxhokaxhiu** [comment]
Another way is to just skip tests to be built by defining the CMake flag `-DYAML_CPP_BUILD_TESTS=0`

**Comment by gruenich** [comment]
This issues should have been closed six years ago!

**Comment by SGSSGene** [comment]
> This issues should have been closed six years ago!

Thank you!
