### ISSUE TITLE
Latest change result in dll.h not found error

### ISSUE THREAD

**Issue by manoj-freyr** [jbeder/yaml-cpp#1036]
With recent changes , da1c8d360e6b9ba8f1bc291728263548a8e30698, removing dll.h from the source code and using generate_export_header to generate dll.h is not working as it fails to generate dll.h and I am erroring out with errors in my main CMakeList with,
 fatal error: 'yaml-cpp/dll.h' file not found
#include "yaml-cpp/dll.h"

**Comment by jimmieliu** [comment]
same here

**Comment by jimmieliu** [comment]
@manoj-freyr build with tag=yaml-cpp-0.7.0 could avoid the recent update

**Comment by jbeder** [comment]
Could you post the full error message please?

**Comment by manoj-freyr** [comment]
Context: I am using yaml-cpp as external project via ExternalProject_Add(). Earlier dll.h was part of source tree in include/yaml-cpp/dll.h and references in the my own client code pointed to #include<yaml-cpp/dll.h> . My include_directories() was having yaml-src/include. And all worked well.

With latest change, the dll.h will be created in build/include/yaml-cpp folder. This breaks my code build unless I add build/include/yaml-cpp to include_directories().
It results in errors like ,
include/yaml-cpp/node/node.h:13:10: fatal error: 'yaml-cpp/dll.h' file not found
 #include "yaml-cpp/dll.h"

PS: Adding build/include/yaml-cpp to include_directories() fixes the error. Is this right enough way?

**Comment by pinotree** [comment]
> Context: I am using yaml-cpp as external project via ExternalProject_Add(). Earlier dll.h was part of source tree in include/yaml-cpp/dll.h and references in the my own client code pointed to #include<yaml-cpp/dll.h> . My include_directories() was having yaml-src/include. And all worked well.

`ExternalProject_Add()` is basically "build that other project as if it was an embedded code copy". Hence, the burden on making sure that you use the "embedded copy" is yours, and it includes using the copy properly.

> With latest change, the dll.h will be created in build/include/yaml-cpp folder. This breaks my code build unless I add build/include/yaml-cpp to include_directories(). It results in errors like , include/yaml-cpp/node/node.h:13:10: fatal error: 'yaml-cpp/dll.h' file not found #include "yaml-cpp/dll.h"

Now `dll.h` is generated by cmake, so it is correctly placed in the build directory.

> PS: Adding build/include/yaml-cpp to include_directories() fixes the error. Is this right enough way?

Since you embed yaml-cpp (via `ExternalProject_Add()`), yes, that's what you have to do.

**Comment by pinotree** [comment]
Also, forgot to ask: please provide full references to your sources. Without them, it is hard to debug why it fails by only a "this commit breaks, here is a single line error string".

**Comment by jbeder** [comment]
Thanks for the explanation, @pinotree. It sounds like the original PR was correct, but may break end-users who had misconfigured setups (e.g. using `ExternalProject-Add` but not `include_directories` `build/include/yaml-cpp`) - is that correct?

If so, I think resubmitting the change is fine, and it would be nice to add some documentation in the README about how to include `yaml-cpp` from another project, including a note about this way.

**Comment by manoj-freyr** [comment]
@pinotree @jbeder Yes since I am using it as external project, handling it the way I mentioned above works.
@pinotree I will make sure I add detailed description in the issue description. Thanks for the detailed answer.
